config/routes.rb
Rails.application.routes.draw do
  resources :rates
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rate.rb
class Rate < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  def index
    @rates = Rate.all
  end

  def show
    @rate = Rate.find(params[:id])
  end

  def new
    @rate = Rate.new
  end

  def create
  rate = Rate.new(rate_params)
  rate.length = params[:length]
  rate.save
  redirect_to rates_path
  end

  def edit
   @rate = Rate.find(params[:id])
  end

  def update
    @rate = Rate.find(params[:id])
    @rate.update(rate_params)
    redirect_to rates_path
  end

  def destroy
    @rate = Rate.find(params[:id])
    @rate.destroy
    redirect_to rates_path
  end

  private
  def rate_params
  params.require(:rate).permit(:loan_type, :length, :rate, :apr, :description)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Perfect Borrower</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <a href="/"><%=image_tag("anaytics_icon.png", class:"logo")%></a>
    <nav>
      <a href="/">Home</a>
      <a href="/rates">Daily Rates</a>
    </nav>

    <%= yield %>

      <footer>
        <p>(c) The Perfect Borrower 2016</p>
      </footer>
  </body>
</html>

app/views/rates/edit.html.erb
<div class="body">

<%= form_for @rate do |f| %>
Loan Type: <%= f.select(:loan_type, [
  ["Conforming", "Conforming"],
  ["High Balance Conforming", "High Balance Conforming"],
  ["Jumbo", "Jumbo"]])%>
  <br><br>
    <%= f.radio_button(:length, "15 Year Fixed") %>
    <%= label_tag(:length_15_year, "15 Year Fixed") %>
    <br>
    <%= f.radio_button(:length, "30 Year Fixed") %>
    <%= label_tag(:length_30_year, "30 Year Fixed") %>
    <br>
    <%= f.radio_button(:length, "5 Year Arm") %>
    <%= label_tag(:length_5_year_arm, "5 Year Arm") %>
    <br>
    <%= f.radio_button(:length, "7 Year Arm") %>
    <%= label_tag(:length_7_year_arm, "7 Year Arm") %>
    <br>
    <%= f.radio_button(:length, "10 Year Arm") %>
    <%= label_tag(:length_10_year_arm, "10 Year Arm") %>
  <br><br>
  <%= f.label :rate %>
  <%= f.text_field :rate %>
  <br><br>
  <%= f.label :apr %>
  <%= f.text_field :apr %>
  <br><br>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br><br>

  <%= f.submit %>
<% end %>

</div>

app/views/rates/index.html.erb
<div class="top">
  <h1>Daily Deals</h1>
  <button class="add"><%= link_to "Add New Deal (+)", new_rate_path %></button>
</div>
<div class="holder">
  <% @rates.each do |rate| %>
    <div class="box">
      <h2><%= rate.loan_type %></h2>
      <p><%= rate.length%></p>
      <p><%= rate.apr%></p>
      <p><%= rate.rate%></p>
      <p><%= rate.description%></p>
      <div>
        <button><%= link_to 'Remove', rate_path(rate),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></button>
        <button><%= link_to 'Edit', edit_rate_url(rate)%></button>
      </div>
    </div>
  <% end %>
</div>

app/views/rates/new.html.erb
<div class="body">

<%= form_for @rate do |f| %>
Loan Type: <%= f.select(:loan_type, [
  ["Conforming", "Conforming"],
  ["High Balance Conforming", "High Balance Conforming"],
  ["Jumbo", "Jumbo"]])%>
  <br><br>

  <%= f.label :rate %>
  <%= f.text_field :rate %>
  <br><br>
  <%= f.label :apr %>
  <%= f.text_field :apr %>
  <br><br>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br><br>
    <%= radio_button_tag(:length, "15 Year Fixed") %>
    <%= label_tag(:length_15_year, "15 Year Fixed") %>
    <br>
    <%= radio_button_tag(:length, "30 Year Fixed") %>
    <%= label_tag(:length_30_year, "30 Year Fixed") %>
    <br>
    <%= radio_button_tag(:length, "5 Year Arm") %>
    <%= label_tag(:length_5_year_arm, "5 Year Arm") %>
    <br>
    <%= radio_button_tag(:length, "7 Year Arm") %>
    <%= label_tag(:length_7_year_arm, "7 Year Arm") %>
    <br>
    <%= radio_button_tag(:length, "10 Year Arm") %>
    <%= label_tag(:length_10_year_arm, "10 Year Arm") %>
  <br><br>

  <%= f.submit %>
<% end %>




</div>

app/views/rates/show.html.erb
<h2><%= link_to "Rates", rates_path %></h2>
<h3><%= @rate.loan_type %></h3>
<p><%= @rate.length %></p>
<p><%= @rate.rate %></p>
<p><%= @rate.apr %></p>
<p><%= @rate.description %></p>